---
output:
  sort-results: true

linters-settings:
  cyclop:
    max-complexity: 15
  goheader:
    values:
      const:
        ORGANIZATION: Deutsche Telekom MMS GmbH
    template: |-
      Copyright {{ YEAR-RANGE }} {{ ORGANIZATION }}
      SPDX-License-Identifier: MIT
  gomnd:
    ignore-functions:
      - "strconv.*"
    ignored-numbers: ["16"]
  goimports:
    local-prefixes: git.t-systems-mms.com
  misspell:
    locale: US

linters:
  disable-all: false
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - decorder
    - errorlint
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - goheader
    - goimports
    - gomnd
    - gosec
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - wrapcheck
    - wsl

issues:
  exclude-rules:
    - path: _linux.go
      linters:
        - goheader
